### ISSUE TITLE
Cannot import config from one realm or a sub-realm 

### ISSUE THREAD

**Issue by debasisdwivedy** [rockcarver/frodo-cli#449]
## Frodo CLI version
Provide output of `frodo -v`

```
You are running the homebrew release.
cli: v2.1.0
lib: v2.2.0
node: v20.11.1
```

## Describe the issue
We are trying to import all the config specific to a particular realm using FRODO.
There is a command for full export as below:
`frodo config export -kAD cloud https://<HOSTNAME>:<PORT>/am <REALM> <USERNAME> <PASSWORD>`

The problem is as below:

a) The command above does not import config specific to a particular realm. It exports all the config irrespective of what realm is passed to the command.

b) In the full export it is not able to export sub-realm. For Example, if there are realm as [/admin,/customer,/customer/XYZ] , then the export contains realm config of [/admin,/customer] but not [/customer/XYZ].

Is it possible to do a full export using a single command for a particular realm or sub-realm.

If not, would it be possible to add this functionality.

Regards,
Debasis

**Comment by phalestrivir** [comment]
@debasisdwivedy 

a) Yes, this is not supported at the moment, it just exports all the realms and not a particular realm, but we can easily add this functionality.

b) This is interesting because when I've tested it on my local test instance of AM it is able to export sub-realms as far as I can tell. For the example you provided, you should see under the "realm" directory three more directories named "root-admin", "root-customer", and "root-customer-XYZ". If you don't see the "root-customer-XYZ" directory, there very well could be a bug, although we would need more information to know what the problem is since I haven't run into any problems with sub-realms before. If you run this command `frodo config export -kAD cloud https://<HOSTNAME>:<PORT>/am > out.txt 2>&1` (this prints all output to a file named out.txt so you can see all the errors without them being overwritten by the progress indicators) do you see any errors that seem related to the issue you are running into? You can also try running the command with `--debug`, `--verbose`, and/or `--curlirize` to print out other information that may be helpful in debugging the problem.
